<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<Folder Include="wwwroot\img\" />
		<Folder Include="wwwroot\js\" />
		<Folder Include="wwwroot\css\" />
		<Folder Include="wwwroot\lib\" />
	</ItemGroup>

	<ItemGroup>
		<!-- Remover duplicados -->
		<Content Remove="wwwroot\css\site.css" />
		<Content Remove="wwwroot\js\site.js" />
		<Content Remove="wwwroot\favicon.ico" />
		<Content Remove="wwwroot\img\hero-runner.jpg" />
		<Content Remove="wwwroot\lib\**" />
	</ItemGroup>

	<ItemGroup>
		<!-- Re-incluir sólo el site.css que tú controlas -->
		<Content Include="wwwroot\css\site.css" CopyToOutputDirectory="PreserveNewest" />
		<Content Include="wwwroot\js\site.js" CopyToOutputDirectory="PreserveNewest" />
		<Content Include="wwwroot\favicon.ico" CopyToOutputDirectory="PreserveNewest" />
		<Content Include="wwwroot\img\hero-runner.jpg" CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="8.0.10" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.9">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.9" />
		<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.7" />
	</ItemGroup>

</Project> 
