// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MomiaTrainSync.Infrastructure.Persistence;

#nullable disable

namespace MomiaTrainSync.Infrastructure.Migrations
{
    [DbContext(typeof(MomiaTrainSyncDbContext))]
    [Migration("20251105214115_TablaDeEntrenadorAtleta")]
    partial class TablaDeEntrenadorAtleta
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.EntrenadorAtletaEnt", b =>
                {
                    b.Property<int>("IdEntrenador")
                        .HasColumnType("int");

                    b.Property<int>("IdAtleta")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("IdEntrenador", "IdAtleta");

                    b.HasIndex("IdAtleta");

                    b.ToTable("EntrenadorAtleta", (string)null);
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.LogErrorEnt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ExcepcionInterna")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrazaError")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LogErrores");
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.PermisoEnt", b =>
                {
                    b.Property<int>("IdPermiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPermiso"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Ruta")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdPermiso");

                    b.ToTable("Permiso", (string)null);

                    b.HasData(
                        new
                        {
                            IdPermiso = -1,
                            Categoria = "Admin",
                            Codigo = "GESTIONAR_USUARIOS",
                            Descripcion = "Permite administrar usuarios del sistema",
                            Estado = true,
                            Ruta = "/Admin/ManageUsers"
                        },
                        new
                        {
                            IdPermiso = -2,
                            Categoria = "Trainer",
                            Codigo = "GESTIONAR_ATLETAS",
                            Descripcion = "Permite gestionar atletas",
                            Estado = true,
                            Ruta = "/Trainer/ManageAthletes"
                        },
                        new
                        {
                            IdPermiso = -3,
                            Categoria = "Profile",
                            Codigo = "VER_PERFIL",
                            Descripcion = "Permite ver el perfil del usuario",
                            Estado = true,
                            Ruta = "/Profile/MyProfile"
                        },
                        new
                        {
                            IdPermiso = -4,
                            Categoria = "Profile",
                            Codigo = "EDITAR_PERFIL",
                            Descripcion = "Permite editar el perfil del usuario",
                            Estado = true,
                            Ruta = "/Profile/EditProfile"
                        },
                        new
                        {
                            IdPermiso = -5,
                            Categoria = "Profile",
                            Codigo = "CAMBIAR_CONTRASENNA_PERFIL",
                            Descripcion = "Permite cambiar la contraseña del usuario",
                            Estado = true,
                            Ruta = "/Profile/ChangePassword"
                        });
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.RolEnt", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdRol");

                    b.ToTable("Rol", (string)null);

                    b.HasData(
                        new
                        {
                            IdRol = -1,
                            Descripcion = "Acceso completo al sistema",
                            Nombre = "Administrador"
                        },
                        new
                        {
                            IdRol = -2,
                            Descripcion = "Gestión de entrenamientos y seguimiento de atletas",
                            Nombre = "Entrenador"
                        },
                        new
                        {
                            IdRol = -3,
                            Descripcion = "Acceso básico a funcionalidades del sistema",
                            Nombre = "Atleta"
                        });
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.RolPermisoEnt", b =>
                {
                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<int>("IdPermiso")
                        .HasColumnType("int");

                    b.HasKey("IdRol", "IdPermiso");

                    b.HasIndex("IdPermiso");

                    b.ToTable("RolPermiso", (string)null);

                    b.HasData(
                        new
                        {
                            IdRol = -1,
                            IdPermiso = -1
                        },
                        new
                        {
                            IdRol = -1,
                            IdPermiso = -2
                        },
                        new
                        {
                            IdRol = -1,
                            IdPermiso = -3
                        },
                        new
                        {
                            IdRol = -1,
                            IdPermiso = -4
                        },
                        new
                        {
                            IdRol = -1,
                            IdPermiso = -5
                        },
                        new
                        {
                            IdRol = -2,
                            IdPermiso = -2
                        },
                        new
                        {
                            IdRol = -2,
                            IdPermiso = -3
                        },
                        new
                        {
                            IdRol = -2,
                            IdPermiso = -4
                        },
                        new
                        {
                            IdRol = -2,
                            IdPermiso = -5
                        },
                        new
                        {
                            IdRol = -3,
                            IdPermiso = -3
                        },
                        new
                        {
                            IdRol = -3,
                            IdPermiso = -4
                        },
                        new
                        {
                            IdRol = -3,
                            IdPermiso = -5
                        });
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.UsuarioEnt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContrasennaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaCumpleannos")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.EntrenadorAtletaEnt", b =>
                {
                    b.HasOne("MomiaTrainSync.Domain.Entities.UsuarioEnt", "Atleta")
                        .WithMany("EntrenadoresAsignados")
                        .HasForeignKey("IdAtleta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MomiaTrainSync.Domain.Entities.UsuarioEnt", "Entrenador")
                        .WithMany("AtletasAsignados")
                        .HasForeignKey("IdEntrenador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Atleta");

                    b.Navigation("Entrenador");
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.RolPermisoEnt", b =>
                {
                    b.HasOne("MomiaTrainSync.Domain.Entities.PermisoEnt", "Permiso")
                        .WithMany("RolPermisos")
                        .HasForeignKey("IdPermiso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MomiaTrainSync.Domain.Entities.RolEnt", "Rol")
                        .WithMany("RolPermisos")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.UsuarioEnt", b =>
                {
                    b.HasOne("MomiaTrainSync.Domain.Entities.RolEnt", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.PermisoEnt", b =>
                {
                    b.Navigation("RolPermisos");
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.RolEnt", b =>
                {
                    b.Navigation("RolPermisos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.UsuarioEnt", b =>
                {
                    b.Navigation("AtletasAsignados");

                    b.Navigation("EntrenadoresAsignados");
                });
#pragma warning restore 612, 618
        }
    }
}
