// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MomiaTrainSync.Infrastructure.Persistence;

#nullable disable

namespace MomiaTrainSync.Infrastructure.Migrations
{
    [DbContext(typeof(MomiaTrainSyncDbContext))]
    [Migration("20260416221331_EntidadUsuarioModificada")]
    partial class EntidadUsuarioModificada
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.EntrenadorAtleta.EntrenadorAtletaEnt", b =>
                {
                    b.Property<int>("IdRelacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRelacion"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdAtleta")
                        .HasColumnType("int");

                    b.Property<int>("IdEntrenador")
                        .HasColumnType("int");

                    b.HasKey("IdRelacion");

                    b.HasIndex("IdAtleta");

                    b.HasIndex("IdEntrenador");

                    b.ToTable("EntrenadorAtleta", (string)null);
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.EntrenamientosZonas.DetalleZonaPlanEnt", b =>
                {
                    b.Property<int>("IdDetalleZonaPlan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalleZonaPlan"));

                    b.Property<int>("IdEntrenamiento")
                        .HasColumnType("int");

                    b.Property<int>("IdZona")
                        .HasColumnType("int");

                    b.Property<int>("MinutosPlanificados")
                        .HasColumnType("int");

                    b.HasKey("IdDetalleZonaPlan");

                    b.HasIndex("IdEntrenamiento");

                    b.HasIndex("IdZona");

                    b.ToTable("DetalleZonaPlan", (string)null);
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.EntrenamientosZonas.EntrenamientoEnt", b =>
                {
                    b.Property<int>("IdEntrenamiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEntrenamiento"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<int>("DuracionEstimada")
                        .HasColumnType("int");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("FechaProgramada")
                        .HasColumnType("date");

                    b.Property<int>("IdRutina")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoSesion")
                        .HasColumnType("int");

                    b.Property<byte>("NivelEsfuerzoEsperado")
                        .HasColumnType("tinyint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Objetivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdEntrenamiento");

                    b.HasIndex("IdRutina");

                    b.HasIndex("IdTipoSesion");

                    b.ToTable("Entrenamiento", (string)null);
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.EntrenamientosZonas.ZonaEntrenamientoEnt", b =>
                {
                    b.Property<int>("IdZona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdZona"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Factor")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdZona");

                    b.ToTable("ZonaEntrenamiento", (string)null);
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.LogErrorEnt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ExcepcionInterna")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrazaError")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LogErrores");
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.RutinasAsignaciones.RutinaEnt", b =>
                {
                    b.Property<int>("IdRutina")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRutina"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdRelacion")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("IdRutina");

                    b.HasIndex("IdRelacion");

                    b.ToTable("Rutina", (string)null);
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.RutinasEntrenamientos.TipoSesionEnt", b =>
                {
                    b.Property<int>("IdTipoSesion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoSesion"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdTipoSesion");

                    b.ToTable("TipoSesion", (string)null);
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.SesionesEntrenamiento.DetalleZonaSesionEnt", b =>
                {
                    b.Property<int>("IdDetalleZonaSesion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalleZonaSesion"));

                    b.Property<int>("IdSesion")
                        .HasColumnType("int");

                    b.Property<int>("IdZona")
                        .HasColumnType("int");

                    b.Property<int>("MinutosCompletados")
                        .HasColumnType("int");

                    b.HasKey("IdDetalleZonaSesion");

                    b.HasIndex("IdSesion");

                    b.HasIndex("IdZona");

                    b.ToTable("DetalleZonaSesion", (string)null);
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.SesionesEntrenamiento.SesionEntrenamientoEnt", b =>
                {
                    b.Property<int>("IdSesion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSesion"));

                    b.Property<decimal>("CargaTotal")
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("Comentarios")
                        .HasColumnType("text");

                    b.Property<int>("DuracionReal")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaEjecucion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEntrenamiento")
                        .HasColumnType("int");

                    b.Property<byte>("NivelEsfuerzoPercibido")
                        .HasColumnType("tinyint");

                    b.HasKey("IdSesion");

                    b.HasIndex("IdEntrenamiento");

                    b.ToTable("SesionEntrenamiento", (string)null);
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.UsuariosRoles.PermisoEnt", b =>
                {
                    b.Property<int>("IdPermiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPermiso"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Ruta")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdPermiso");

                    b.ToTable("Permiso", (string)null);
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.UsuariosRoles.RolEnt", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdRol");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Rol", (string)null);
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.UsuariosRoles.RolPermisoEnt", b =>
                {
                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<int>("IdPermiso")
                        .HasColumnType("int");

                    b.HasKey("IdRol", "IdPermiso");

                    b.HasIndex("IdPermiso");

                    b.ToTable("RolPermiso", (string)null);
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.UsuariosRoles.UsuarioEnt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Biografia")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ContrasennaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaUltimoCambioContrasenna")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaUltimoLogin")
                        .HasColumnType("datetime");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.EntrenadorAtleta.EntrenadorAtletaEnt", b =>
                {
                    b.HasOne("MomiaTrainSync.Domain.Entities.UsuariosRoles.UsuarioEnt", "Atleta")
                        .WithMany("EntrenamientosComoAtleta")
                        .HasForeignKey("IdAtleta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_EntrenadorAtleta_Atleta");

                    b.HasOne("MomiaTrainSync.Domain.Entities.UsuariosRoles.UsuarioEnt", "Entrenador")
                        .WithMany("EntrenamientosComoEntrenador")
                        .HasForeignKey("IdEntrenador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_EntrenadorAtleta_Entrenador");

                    b.Navigation("Atleta");

                    b.Navigation("Entrenador");
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.EntrenamientosZonas.DetalleZonaPlanEnt", b =>
                {
                    b.HasOne("MomiaTrainSync.Domain.Entities.EntrenamientosZonas.EntrenamientoEnt", "Entrenamiento")
                        .WithMany("DetallesZonaPlan")
                        .HasForeignKey("IdEntrenamiento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MomiaTrainSync.Domain.Entities.EntrenamientosZonas.ZonaEntrenamientoEnt", "Zona")
                        .WithMany("DetalleZonaPlanes")
                        .HasForeignKey("IdZona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entrenamiento");

                    b.Navigation("Zona");
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.EntrenamientosZonas.EntrenamientoEnt", b =>
                {
                    b.HasOne("MomiaTrainSync.Domain.Entities.RutinasAsignaciones.RutinaEnt", "Rutina")
                        .WithMany("Entrenamientos")
                        .HasForeignKey("IdRutina")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MomiaTrainSync.Domain.Entities.RutinasEntrenamientos.TipoSesionEnt", "TipoSesion")
                        .WithMany("Entrenamientos")
                        .HasForeignKey("IdTipoSesion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rutina");

                    b.Navigation("TipoSesion");
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.RutinasAsignaciones.RutinaEnt", b =>
                {
                    b.HasOne("MomiaTrainSync.Domain.Entities.EntrenadorAtleta.EntrenadorAtletaEnt", "Relacion")
                        .WithMany("Rutinas")
                        .HasForeignKey("IdRelacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Relacion");
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.SesionesEntrenamiento.DetalleZonaSesionEnt", b =>
                {
                    b.HasOne("MomiaTrainSync.Domain.Entities.SesionesEntrenamiento.SesionEntrenamientoEnt", "Sesion")
                        .WithMany("DetallesZona")
                        .HasForeignKey("IdSesion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MomiaTrainSync.Domain.Entities.EntrenamientosZonas.ZonaEntrenamientoEnt", "Zona")
                        .WithMany("DetalleZonaSesiones")
                        .HasForeignKey("IdZona")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sesion");

                    b.Navigation("Zona");
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.SesionesEntrenamiento.SesionEntrenamientoEnt", b =>
                {
                    b.HasOne("MomiaTrainSync.Domain.Entities.EntrenamientosZonas.EntrenamientoEnt", "Entrenamiento")
                        .WithMany("Sesiones")
                        .HasForeignKey("IdEntrenamiento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Entrenamiento");
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.UsuariosRoles.RolPermisoEnt", b =>
                {
                    b.HasOne("MomiaTrainSync.Domain.Entities.UsuariosRoles.PermisoEnt", "Permiso")
                        .WithMany("RolPermisos")
                        .HasForeignKey("IdPermiso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MomiaTrainSync.Domain.Entities.UsuariosRoles.RolEnt", "Rol")
                        .WithMany("RolPermisos")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.UsuariosRoles.UsuarioEnt", b =>
                {
                    b.HasOne("MomiaTrainSync.Domain.Entities.UsuariosRoles.RolEnt", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.EntrenadorAtleta.EntrenadorAtletaEnt", b =>
                {
                    b.Navigation("Rutinas");
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.EntrenamientosZonas.EntrenamientoEnt", b =>
                {
                    b.Navigation("DetallesZonaPlan");

                    b.Navigation("Sesiones");
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.EntrenamientosZonas.ZonaEntrenamientoEnt", b =>
                {
                    b.Navigation("DetalleZonaPlanes");

                    b.Navigation("DetalleZonaSesiones");
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.RutinasAsignaciones.RutinaEnt", b =>
                {
                    b.Navigation("Entrenamientos");
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.RutinasEntrenamientos.TipoSesionEnt", b =>
                {
                    b.Navigation("Entrenamientos");
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.SesionesEntrenamiento.SesionEntrenamientoEnt", b =>
                {
                    b.Navigation("DetallesZona");
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.UsuariosRoles.PermisoEnt", b =>
                {
                    b.Navigation("RolPermisos");
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.UsuariosRoles.RolEnt", b =>
                {
                    b.Navigation("RolPermisos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.UsuariosRoles.UsuarioEnt", b =>
                {
                    b.Navigation("EntrenamientosComoAtleta");

                    b.Navigation("EntrenamientosComoEntrenador");
                });
#pragma warning restore 612, 618
        }
    }
}
