// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MomiaTrainSync.Infrastructure.Persistence;

#nullable disable

namespace MomiaTrainSync.Infrastructure.Migrations
{
    [DbContext(typeof(MomiaTrainSyncDbContext))]
    partial class MomiaTrainSyncDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.PermisoEnt", b =>
                {
                    b.Property<int>("IdPermiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPermiso"));

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdPermiso");

                    b.ToTable("Permiso", (string)null);

                    b.HasData(
                        new
                        {
                            IdPermiso = -1,
                            Estado = true,
                            Nombre = "GestionarUsuarios"
                        },
                        new
                        {
                            IdPermiso = -2,
                            Estado = true,
                            Nombre = "GestionarEntrenamientos"
                        },
                        new
                        {
                            IdPermiso = -3,
                            Estado = true,
                            Nombre = "VerReportes"
                        },
                        new
                        {
                            IdPermiso = -4,
                            Estado = true,
                            Nombre = "EditarPerfil"
                        },
                        new
                        {
                            IdPermiso = -5,
                            Estado = true,
                            Nombre = "VerRutina"
                        });
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.RolEnt", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdRol");

                    b.ToTable("Rol", (string)null);

                    b.HasData(
                        new
                        {
                            IdRol = -1,
                            Descripcion = "Acceso completo al sistema",
                            Nombre = "Administrador"
                        },
                        new
                        {
                            IdRol = -2,
                            Descripcion = "Gestión de entrenamientos y seguimiento de atletas",
                            Nombre = "Entrenador"
                        },
                        new
                        {
                            IdRol = -3,
                            Descripcion = "Acceso básico a funcionalidades del sistema",
                            Nombre = "Atleta"
                        });
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.RolPermisoEnt", b =>
                {
                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<int>("IdPermiso")
                        .HasColumnType("int");

                    b.HasKey("IdRol", "IdPermiso");

                    b.HasIndex("IdPermiso");

                    b.ToTable("RolPermiso", (string)null);

                    b.HasData(
                        new
                        {
                            IdRol = -1,
                            IdPermiso = -1
                        },
                        new
                        {
                            IdRol = -1,
                            IdPermiso = -2
                        },
                        new
                        {
                            IdRol = -1,
                            IdPermiso = -3
                        },
                        new
                        {
                            IdRol = -1,
                            IdPermiso = -4
                        },
                        new
                        {
                            IdRol = -1,
                            IdPermiso = -5
                        },
                        new
                        {
                            IdRol = -2,
                            IdPermiso = -2
                        },
                        new
                        {
                            IdRol = -2,
                            IdPermiso = -3
                        },
                        new
                        {
                            IdRol = -2,
                            IdPermiso = -4
                        },
                        new
                        {
                            IdRol = -2,
                            IdPermiso = -5
                        },
                        new
                        {
                            IdRol = -3,
                            IdPermiso = -4
                        },
                        new
                        {
                            IdRol = -3,
                            IdPermiso = -5
                        });
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.UsuarioEnt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContrasennaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.RolPermisoEnt", b =>
                {
                    b.HasOne("MomiaTrainSync.Domain.Entities.PermisoEnt", "Permiso")
                        .WithMany("RolesPermisos")
                        .HasForeignKey("IdPermiso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MomiaTrainSync.Domain.Entities.RolEnt", "Rol")
                        .WithMany("RolesPermisos")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.UsuarioEnt", b =>
                {
                    b.HasOne("MomiaTrainSync.Domain.Entities.RolEnt", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.PermisoEnt", b =>
                {
                    b.Navigation("RolesPermisos");
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.RolEnt", b =>
                {
                    b.Navigation("RolesPermisos");

                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
