// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MomiaTrainSync.Infrastructure.Persistence;

#nullable disable

namespace MomiaTrainSync.Infrastructure.Migrations
{
    [DbContext(typeof(MomiaTrainSyncDbContext))]
    partial class MomiaTrainSyncDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.EntrenadorAtleta.EntrenadorAtletaEnt", b =>
                {
                    b.Property<int>("IdRelacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRelacion"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdAtleta")
                        .HasColumnType("int");

                    b.Property<int>("IdEntrenador")
                        .HasColumnType("int");

                    b.HasKey("IdRelacion");

                    b.HasIndex("IdAtleta");

                    b.HasIndex("IdEntrenador");

                    b.ToTable("EntrenadorAtleta", (string)null);
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.EntrenamientosZonas.DetalleZonaPlanEnt", b =>
                {
                    b.Property<int>("IdDetalleZonaPlan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalleZonaPlan"));

                    b.Property<int>("IdEntrenamiento")
                        .HasColumnType("int");

                    b.Property<int>("IdZona")
                        .HasColumnType("int");

                    b.Property<int>("MinutosPlanificados")
                        .HasColumnType("int");

                    b.HasKey("IdDetalleZonaPlan");

                    b.HasIndex("IdEntrenamiento");

                    b.HasIndex("IdZona");

                    b.ToTable("DetalleZonaPlan", (string)null);
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.EntrenamientosZonas.EntrenamientoEnt", b =>
                {
                    b.Property<int>("IdEntrenamiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEntrenamiento"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<int>("DuracionEstimada")
                        .HasColumnType("int");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("FechaProgramada")
                        .HasColumnType("date");

                    b.Property<int>("IdRutina")
                        .HasColumnType("int");

                    b.Property<byte>("NivelEsfuerzoEsperado")
                        .HasColumnType("tinyint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Objetivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TipoSesion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdEntrenamiento");

                    b.HasIndex("IdRutina");

                    b.ToTable("Entrenamiento", (string)null);
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.EntrenamientosZonas.ZonaEntrenamientoEnt", b =>
                {
                    b.Property<int>("IdZona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdZona"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Factor")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdZona");

                    b.ToTable("ZonaEntrenamiento", (string)null);
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.LogErrorEnt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ExcepcionInterna")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrazaError")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LogErrores");
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.RutinasAsignaciones.RutinaEnt", b =>
                {
                    b.Property<int>("IdRutina")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRutina"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdRelacion")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("IdRutina");

                    b.HasIndex("IdRelacion");

                    b.ToTable("Rutina", (string)null);
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.SesionesEntrenamiento.DetalleZonaSesionEnt", b =>
                {
                    b.Property<int>("IdDetalleZonaSesion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalleZonaSesion"));

                    b.Property<int>("IdSesion")
                        .HasColumnType("int");

                    b.Property<int>("IdZona")
                        .HasColumnType("int");

                    b.Property<int>("MinutosCompletados")
                        .HasColumnType("int");

                    b.HasKey("IdDetalleZonaSesion");

                    b.HasIndex("IdSesion");

                    b.HasIndex("IdZona");

                    b.ToTable("DetalleZonaSesion", (string)null);
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.SesionesEntrenamiento.SesionEntrenamientoEnt", b =>
                {
                    b.Property<int>("IdSesion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSesion"));

                    b.Property<decimal>("CargaTotal")
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("Comentarios")
                        .HasColumnType("text");

                    b.Property<int>("DuracionReal")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaEjecucion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEntrenamiento")
                        .HasColumnType("int");

                    b.Property<byte>("NivelEsfuerzoPercibido")
                        .HasColumnType("tinyint");

                    b.HasKey("IdSesion");

                    b.HasIndex("IdEntrenamiento");

                    b.ToTable("SesionEntrenamiento", (string)null);
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.UsuariosRoles.PermisoEnt", b =>
                {
                    b.Property<int>("IdPermiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPermiso"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Ruta")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdPermiso");

                    b.ToTable("Permiso", (string)null);

                    b.HasData(
                        new
                        {
                            IdPermiso = -1,
                            Categoria = "Users",
                            Codigo = "GESTIONAR_USUARIOS",
                            Descripcion = "Permite administrar usuarios del sistema",
                            Estado = true,
                            Ruta = "/Users/ManageUsers"
                        },
                        new
                        {
                            IdPermiso = -2,
                            Categoria = "Athletes",
                            Codigo = "GESTIONAR_ATLETAS",
                            Descripcion = "Permite gestionar atletas",
                            Estado = true,
                            Ruta = "/Trainer/ManageAthletes"
                        },
                        new
                        {
                            IdPermiso = -3,
                            Categoria = "Profile",
                            Codigo = "VER_PERFIL",
                            Descripcion = "Permite ver el perfil del usuario",
                            Estado = true,
                            Ruta = "/Profile/MyProfile"
                        },
                        new
                        {
                            IdPermiso = -4,
                            Categoria = "Profile",
                            Codigo = "EDITAR_PERFIL",
                            Descripcion = "Permite editar el perfil del usuario",
                            Estado = true,
                            Ruta = "/Profile/EditProfile"
                        },
                        new
                        {
                            IdPermiso = -5,
                            Categoria = "Profile",
                            Codigo = "CAMBIAR_CONTRASENNA_PERFIL",
                            Descripcion = "Permite cambiar la contraseña del usuario",
                            Estado = true,
                            Ruta = "/Profile/ChangePassword"
                        },
                        new
                        {
                            IdPermiso = -6,
                            Categoria = "Usuarios",
                            Codigo = "AGREGAR_ATLETA_ENTRENADOR",
                            Descripcion = "Permite al entrenador agregar atletas a su lista asignada",
                            Estado = true,
                            Ruta = "/Trainer/AddAthlete"
                        },
                        new
                        {
                            IdPermiso = -7,
                            Categoria = "Usuarios",
                            Codigo = "ELIMINAR_ATLETA_ENTRENADOR",
                            Descripcion = "Permite al entrenador eliminar atletas de su lista",
                            Estado = true,
                            Ruta = "/Trainer/DeleteAthlete"
                        },
                        new
                        {
                            IdPermiso = -8,
                            Categoria = "Security",
                            Codigo = "VER_PERMISOS",
                            Descripcion = "Permite ver la lista de permisos",
                            Estado = true,
                            Ruta = "/Permissions/Index"
                        });
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.UsuariosRoles.RolEnt", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdRol");

                    b.ToTable("Rol", (string)null);

                    b.HasData(
                        new
                        {
                            IdRol = -1,
                            Descripcion = "Acceso completo al sistema",
                            Nombre = "Administrador"
                        },
                        new
                        {
                            IdRol = -2,
                            Descripcion = "Gestiona rutinas, entrenamientos y atletas",
                            Nombre = "Entrenador"
                        },
                        new
                        {
                            IdRol = -3,
                            Descripcion = "Usuario que recibe rutinas asignadas",
                            Nombre = "Atleta"
                        });
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.UsuariosRoles.RolPermisoEnt", b =>
                {
                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<int>("IdPermiso")
                        .HasColumnType("int");

                    b.HasKey("IdRol", "IdPermiso");

                    b.HasIndex("IdPermiso");

                    b.ToTable("RolPermiso", (string)null);

                    b.HasData(
                        new
                        {
                            IdRol = -1,
                            IdPermiso = -1
                        },
                        new
                        {
                            IdRol = -1,
                            IdPermiso = -2
                        },
                        new
                        {
                            IdRol = -1,
                            IdPermiso = -3
                        },
                        new
                        {
                            IdRol = -1,
                            IdPermiso = -4
                        },
                        new
                        {
                            IdRol = -1,
                            IdPermiso = -5
                        },
                        new
                        {
                            IdRol = -1,
                            IdPermiso = -8
                        },
                        new
                        {
                            IdRol = -2,
                            IdPermiso = -2
                        },
                        new
                        {
                            IdRol = -2,
                            IdPermiso = -3
                        },
                        new
                        {
                            IdRol = -2,
                            IdPermiso = -4
                        },
                        new
                        {
                            IdRol = -2,
                            IdPermiso = -5
                        },
                        new
                        {
                            IdRol = -2,
                            IdPermiso = -6
                        },
                        new
                        {
                            IdRol = -2,
                            IdPermiso = -7
                        },
                        new
                        {
                            IdRol = -3,
                            IdPermiso = -3
                        },
                        new
                        {
                            IdRol = -3,
                            IdPermiso = -4
                        },
                        new
                        {
                            IdRol = -3,
                            IdPermiso = -5
                        });
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.UsuariosRoles.UsuarioEnt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContrasennaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaCumpleannos")
                        .HasColumnType("datetime");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Apellido = "Sistema",
                            ContrasennaHash = "UDd9Jxr59YTGLmp8Dofxlw==.Bf/QH105NwCI9Dt8C+fkRpjRXwOlPSEOjVZKMgqK0pI=",
                            Correo = "admin@dominio.com",
                            Estado = true,
                            FechaCreacion = new DateTime(2025, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaCumpleannos = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Admin",
                            RolId = -1,
                            Telefono = "60000000"
                        });
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.EntrenadorAtleta.EntrenadorAtletaEnt", b =>
                {
                    b.HasOne("MomiaTrainSync.Domain.Entities.UsuariosRoles.UsuarioEnt", "Atleta")
                        .WithMany("EntrenamientosComoAtleta")
                        .HasForeignKey("IdAtleta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_EntrenadorAtleta_Atleta");

                    b.HasOne("MomiaTrainSync.Domain.Entities.UsuariosRoles.UsuarioEnt", "Entrenador")
                        .WithMany("EntrenamientosComoEntrenador")
                        .HasForeignKey("IdEntrenador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_EntrenadorAtleta_Entrenador");

                    b.Navigation("Atleta");

                    b.Navigation("Entrenador");
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.EntrenamientosZonas.DetalleZonaPlanEnt", b =>
                {
                    b.HasOne("MomiaTrainSync.Domain.Entities.EntrenamientosZonas.EntrenamientoEnt", "Entrenamiento")
                        .WithMany("DetallesZonaPlan")
                        .HasForeignKey("IdEntrenamiento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MomiaTrainSync.Domain.Entities.EntrenamientosZonas.ZonaEntrenamientoEnt", "Zona")
                        .WithMany("DetalleZonaPlanes")
                        .HasForeignKey("IdZona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entrenamiento");

                    b.Navigation("Zona");
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.EntrenamientosZonas.EntrenamientoEnt", b =>
                {
                    b.HasOne("MomiaTrainSync.Domain.Entities.RutinasAsignaciones.RutinaEnt", "Rutina")
                        .WithMany("Entrenamientos")
                        .HasForeignKey("IdRutina")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rutina");
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.RutinasAsignaciones.RutinaEnt", b =>
                {
                    b.HasOne("MomiaTrainSync.Domain.Entities.EntrenadorAtleta.EntrenadorAtletaEnt", "Relacion")
                        .WithMany("Rutinas")
                        .HasForeignKey("IdRelacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Relacion");
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.SesionesEntrenamiento.DetalleZonaSesionEnt", b =>
                {
                    b.HasOne("MomiaTrainSync.Domain.Entities.SesionesEntrenamiento.SesionEntrenamientoEnt", "Sesion")
                        .WithMany("DetallesZona")
                        .HasForeignKey("IdSesion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MomiaTrainSync.Domain.Entities.EntrenamientosZonas.ZonaEntrenamientoEnt", "Zona")
                        .WithMany("DetalleZonaSesiones")
                        .HasForeignKey("IdZona")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sesion");

                    b.Navigation("Zona");
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.SesionesEntrenamiento.SesionEntrenamientoEnt", b =>
                {
                    b.HasOne("MomiaTrainSync.Domain.Entities.EntrenamientosZonas.EntrenamientoEnt", "Entrenamiento")
                        .WithMany("Sesiones")
                        .HasForeignKey("IdEntrenamiento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Entrenamiento");
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.UsuariosRoles.RolPermisoEnt", b =>
                {
                    b.HasOne("MomiaTrainSync.Domain.Entities.UsuariosRoles.PermisoEnt", "Permiso")
                        .WithMany("RolPermisos")
                        .HasForeignKey("IdPermiso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MomiaTrainSync.Domain.Entities.UsuariosRoles.RolEnt", "Rol")
                        .WithMany("RolPermisos")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.UsuariosRoles.UsuarioEnt", b =>
                {
                    b.HasOne("MomiaTrainSync.Domain.Entities.UsuariosRoles.RolEnt", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.EntrenadorAtleta.EntrenadorAtletaEnt", b =>
                {
                    b.Navigation("Rutinas");
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.EntrenamientosZonas.EntrenamientoEnt", b =>
                {
                    b.Navigation("DetallesZonaPlan");

                    b.Navigation("Sesiones");
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.EntrenamientosZonas.ZonaEntrenamientoEnt", b =>
                {
                    b.Navigation("DetalleZonaPlanes");

                    b.Navigation("DetalleZonaSesiones");
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.RutinasAsignaciones.RutinaEnt", b =>
                {
                    b.Navigation("Entrenamientos");
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.SesionesEntrenamiento.SesionEntrenamientoEnt", b =>
                {
                    b.Navigation("DetallesZona");
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.UsuariosRoles.PermisoEnt", b =>
                {
                    b.Navigation("RolPermisos");
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.UsuariosRoles.RolEnt", b =>
                {
                    b.Navigation("RolPermisos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("MomiaTrainSync.Domain.Entities.UsuariosRoles.UsuarioEnt", b =>
                {
                    b.Navigation("EntrenamientosComoAtleta");

                    b.Navigation("EntrenamientosComoEntrenador");
                });
#pragma warning restore 612, 618
        }
    }
}
