// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MomiaTrainSync.Data;

#nullable disable

namespace MomiaTrainSync.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251019192707_AgregarObjetivoAPlanEntrenamiento")]
    partial class AgregarObjetivoAPlanEntrenamiento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MomiaTrainSync.Models.EntrenadorAtleta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AtletaId")
                        .HasColumnType("int");

                    b.Property<int>("EntrenadorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AtletaId");

                    b.HasIndex("EntrenadorId", "AtletaId")
                        .IsUnique();

                    b.ToTable("EntrenadoresAtletas");
                });

            modelBuilder.Entity("MomiaTrainSync.Models.PlanEntrenamiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdAtleta")
                        .HasColumnType("int");

                    b.Property<int>("IdCreador")
                        .HasColumnType("int");

                    b.Property<string>("Objetivo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("IdAtleta");

                    b.HasIndex("IdCreador");

                    b.ToTable("PlanesEntrenamiento");
                });

            modelBuilder.Entity("MomiaTrainSync.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Contrasena = "123456",
                            Correo = "laura@ejemplo.com",
                            Estado = "Activo",
                            FechaRegistro = new DateTime(2025, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Laura Azofeifa",
                            Rol = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Contrasena = "123456",
                            Correo = "carlos@ejemplo.com",
                            Estado = "Activo",
                            FechaRegistro = new DateTime(2025, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Carlos Ramírez",
                            Rol = "Entrenador"
                        },
                        new
                        {
                            Id = 3,
                            Contrasena = "123456",
                            Correo = "ana@ejemplo.com",
                            Estado = "Activo",
                            FechaRegistro = new DateTime(2025, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Ana Rojas",
                            Rol = "Entrenador"
                        },
                        new
                        {
                            Id = 4,
                            Contrasena = "123456",
                            Correo = "luis@ejemplo.com",
                            Estado = "Activo",
                            FechaRegistro = new DateTime(2025, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Luis Jiménez",
                            Rol = "Atleta"
                        },
                        new
                        {
                            Id = 5,
                            Contrasena = "123456",
                            Correo = "maria@ejemplo.com",
                            Estado = "Activo",
                            FechaRegistro = new DateTime(2025, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "María Pérez",
                            Rol = "Atleta"
                        });
                });

            modelBuilder.Entity("MomiaTrainSync.Models.EntrenadorAtleta", b =>
                {
                    b.HasOne("MomiaTrainSync.Models.Usuario", "Atleta")
                        .WithMany()
                        .HasForeignKey("AtletaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MomiaTrainSync.Models.Usuario", "Entrenador")
                        .WithMany()
                        .HasForeignKey("EntrenadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Atleta");

                    b.Navigation("Entrenador");
                });

            modelBuilder.Entity("MomiaTrainSync.Models.PlanEntrenamiento", b =>
                {
                    b.HasOne("MomiaTrainSync.Models.Usuario", "Atleta")
                        .WithMany()
                        .HasForeignKey("IdAtleta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MomiaTrainSync.Models.Usuario", "Creador")
                        .WithMany()
                        .HasForeignKey("IdCreador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Atleta");

                    b.Navigation("Creador");
                });
#pragma warning restore 612, 618
        }
    }
}
